### ISSUE TITLE
this.stream.setNoDelay is not a function

### ISSUE THREAD

**Issue by RKutynko** [M2Ys4U/socksjs#5]
Tried an example from this Gist [https://gist.github.com/abtris/3eb89a5b8862ee0819f23649420beb55](https://gist.github.com/abtris/3eb89a5b8862ee0819f23649420beb55)
```
Debugger attached.
Waiting for the debugger to disconnect...
<proj name>\node_modules\pg\lib\connection.js:38
    this.stream.setNoDelay(true)
                ^

TypeError: this.stream.setNoDelay is not a function
    at Connection.connect (<proj name>\node_modules\pg\lib\connection.js:38:17)
    at Client._connect (<proj name>\node_modules\pg\lib\client.js:104:11)
    at Client.connect (<proj name>\node_modules\pg\lib\client.js:152:12)
    at Object.<anonymous> (<proj name>\test2.js:40:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Process exited with code 1
```
My packages
```
  "dependencies": {
    "pg": "^8.4.1",
    "socksjs": "^0.5.0"
  },
```

**Comment by RKutynko** [comment]
Figured it out. The problem is with `pg` package. Version "8.x.x" is not supported. Rolled back to "7.18.2" and everything works fine
